source = ~/.config/hypr/conf/variables.conf

background {
    # * Settings for the lock screen background image and its visual effects:
    monitor = HDMI-A-1 # Which monitor to display the background on
    path = $wallpapers/catppuccin-dark-waves.png # Path to the wallpaper image
    blur_passes = 3 # Number of times the blur effect is applied (higher = smoother blur)
    blur_size = 2 # Intensity of the blur effect
    contrast = 1 # Adjust image contrast (1 = original)
    brightness = 0.8 # Adjust brightness (less than 1 = darker)
    vibrancy = 0.16 # Adds color pop; subtle vibrancy effect
    vibrancy_darkness = 0.1 # Darkens the vibrancy effect for subtlety
}

label {
    # * Digital clock displayed on the lock screen:
    monitor = HDMI-A-1 # Which monitor to display the clock
    text = cmd[update:1000] echo "$(date +"%I:%M %p")" #AM/PM
    color = rgb(180, 190, 254)
    font_size = 145
    font_family = JetBrainsMono Nerd Font
    position = 0, -218 # X, Y coordinates on the screen
    halign = center # Horizontal alignment
    valign = top # Vertical alignment
}

label { # Date
    # * Displays the current date below the clock:
    monitor = HDMI-A-1
    text = cmd[update:5000] date +"%A, %B %d" # Runs a command every 5 seconds to update date
    color = rgb(180, 190, 254)
    font_size = 65
    font_family = JetBrainsMono Nerd Font
    position = 0, 32
    halign = center
    valign = center
}

input-field { # Password entry field
    # * Settings for the password input box:
    monitor = HDMI-A-1
    size = 300, 60 # Width and height of input box
    outline_thickness = 2 # Thickness of the box outline
    dots_size = 0.22
    dots_spacing = 0.35
    dots_center = true
    placeholder_text = Enter password
    fail_text = Failed: incorrect password
    outer_color = rgba(0, 0, 0, 0) # Transparent outer border
    inner_color = rgba(0, 0, 0, 0.25) # Background color of input field
    font_color = rgb(205, 214, 244) # Color of typed password
    font_family = JetBrainsMono Nerd Font
    check_color = rgb(166, 227, 161) # Color for dots when password is correct
    position = 0, 105 # Position relative to screen center
    halign = center
    valign = bottom
}

label { # Keyboard Layout
    monitor = HDMI-A-1
    text = $LAYOUT
    color = $color8
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 50
    halign = center
    valign = bottom
}
