# Animation definitions (transitions, easing, workspace effects):
source = ~/.config/hypr/components/animations.conf

# Visual appearance (gaps, borders, opacity):
source = ~/.config/hypr/components/appearance.conf

# Environment variables and session-level configuration
# (e.g., Wayland flags, GTK and cursor themes):
source = ~/.config/hypr/components/env.conf

# Keybindings and input mappings:
source = ~/.config/hypr/components/keybinds.conf

# Core compositor settings
# Includes layout parameters, and misc options:
source = ~/.config/hypr/components/settings.conf

# Autostart applications and background services:
source = ~/.config/hypr/components/startup.conf

