binde = SUPER, T, exec, kitty
binde = SUPER_ALT, T, exec, foot
bind = SUPER, B, exec, firefox
binde = SUPER, E, exec, nautilus
bind = SUPER, O, exec, obsidian
bind = SUPER, F, exec, wofi --show drun

bind = SUPER, f11, fullscreen
bind = SUPER, Space, togglefloating
binde = SUPER, C, killactive
binde = ALT, Tab, cyclenext
bind = SUPER, L, exec, hyprlock
bindl = CTRL, Tab, exec, hyprctl switchxkblayout all next

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4

bind = ALT, 1, movetoworkspace, 1
bind = ALT, 2, movetoworkspace, 2
bind = ALT, 3, movetoworkspace, 3
bind = ALT, 4, movetoworkspace, 4

bind = , Print, exec, hyprshot -m window
bind = SHIFT, Print, exec, hyprshot -m region
bind = CTRL, Print, exec, hyprshot -m output

# :272 = left click:
bindm = SUPER, mouse:272, movewindow

# :273 = right click:
bindm = SUPER, mouse:273, resizewindow
