background {
    # * Settings for the lock screen background image and its visual effects:
    monitor = HDMI-A-1
    path = ~/Wallpapers/mountains.jpg
    blur_passes = 3
    blur_size = 2
    contrast = 1 # Adjust image contrast (1 = original)
    brightness = 0.8 # Adjust brightness (less than 1 = darker)
    vibrancy = 0.16 # Adds color pop; subtle vibrancy effect
    vibrancy_darkness = 0.1
}

input-field { # Password entry field
    # * Settings for the password input box:
    monitor = HDMI-A-1
    size = 300, 60 # Width and height of input box
    outline_thickness = 2 # Thickness of the box outline
    dots_size = 0.22
    dots_spacing = 0.35
    dots_center = true
    placeholder_text = Enter password
    fail_text = Failed: incorrect password
    outer_color = rgba(0, 0, 0, 0) # Transparent outer border
    inner_color = rgba(0, 0, 0, 0.25) # Background color of input field
    font_color = rgb(235, 219, 178) # Color of typed password
    font_family = JetBrainsMono Nerd Font
    check_color = rgb(152, 151, 26) # Color for dots when password is correct
    position = 0, 105
    halign = center
    valign = bottom
}
