# Keybindings configuration

# * Core:
bind = SUPER, T, exec, kitty
bind = SUPER, K, killactive,
bind = SUPER, D, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch >
bind = SUPER, F, exec, thunar
bind = SUPER, M, exec, wofi --show drun
bind = SUPER, B, exec, firefox

# * Move focus with $mainMod(current - SUPER) + arrow keys:
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

# * Switch workspaces with $mainMod + [0-4]:
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4

# * Switch layout:
bind = CTRL, TAB, exec, hyprctl switchxkblayout all next

# * Hyprlock:
bind = SUPER, L, exec, hyprlock

# * Screenshot(grim + slurp):
bind = SHIFT, Print, exec, grim -g "$(slurp)" ~/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png
