source = ~/.config/hypr/conf/variables.conf

# Groups:
$wm=Window Management
$app=Applications
$sys=System
$d=[$wm]

# Core applications:
$d=[$app]

bindd = $mod, T, $d terminal, exec, $term
bindd = ALT, T, $d dropdown terminal, exec, $termAlt
bindd = $mod, E, $d file manager, exec, $fileManager
bindd = $mod, C, $d code editor, exec, $editor
bindd = $mod, B, $d browser, exec, $browser
bindd = $mod, M, $d app launcher, exec, $launcher

# System:
$d=[$sys]

bindd = $mod, L, $d lock screen, exec, hyprlock
bindd = $mod, Delete, $d logout menu, exec, hyde-shell logout
bindd = $mod, D, $d power menu, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# WM:
$d=[$wm]

bindd = $mod, K, $d kill active window, killactive
bindd = $mod, W, $d toggle floating, togglefloating
bindd = $mod, G, $d toggle group, togglegroup
bindd = $modShift, F11, $d fullscreen, fullscreen

$d=[$wm|Focus]

bindd = $mod, Left,  $d focus left, movefocus, l
bindd = $mod, Right, $d focus right, movefocus, r
bindd = $mod, Up,    $d focus up, movefocus, u
bindd = $mod, Down,  $d focus down, movefocus, d
bindd = ALT, Tab,     $d cycle focus, cyclenext

# Workspaces:
$d=[Workspaces]

bindd = $mod, 1, $d workspace 1, workspace, 1
bindd = $mod, 2, $d workspace 2, workspace, 2
bindd = $mod, 3, $d workspace 3, workspace, 3
bindd = $mod, 4, $d workspace 4, workspace, 4

# Layout:
$d=[Input]

bindd = $modCtrl, TAB, $d switch keyboard layout, exec, hyprctl switchxkblayout all next

# Utilities:
$d=[Utilities]

bindd = $modShift, Print, $d screenshot area, exec, hyprshot -m region
bindd = $modCtrl, Print, $d screenshot area, exec, hyprshot -m output
