# Variables:
source = ~/.config/hypr/conf/variables.conf

# Bind Groups (for bindd descriptions):
$grp_app = [Applications]
$grp_sys = [System]
$grp_wm = [Window Management]
$grp_focus = [Window Management|Focus]
$grp_ws = [Workspaces]
$grp_input = [Input]
$grp_utils = [Utilities]


# Applications:
bindd = $mod, T, $grp_app terminal, exec, $term
bindd = $modAlt, T, $grp_app alt terminal, exec, $termAlt

bindd = $mod, E, $grp_app file manager, exec, $fileManager
bindd = $mod, C, $grp_app code editor, exec, $editor
bindd = $mod, B, $grp_app browser, exec, $browser

# App launcher (main entry point for apps):
bindd = $mod, D, $grp_app launcher, exec, $launcher

# Session control and power actions:
bindd = $mod, L, $grp_sys lock screen, exec, hyprlock

# Core window actions:
bindd = $mod, K, $grp_wm close window, killactive
bindd = $mod, F, $grp_wm toggle fullscreen, fullscreen
bindd = $mod, Space, $grp_wm toggle floating, togglefloating
bindd = $mod, G, $grp_wm toggle group, togglegroup

# Directional navigation between windows:
bindd = $mod, Left,  $grp_focus focus left,  movefocus, l
bindd = $mod, Right, $grp_focus focus right, movefocus, r
bindd = $mod, Up,    $grp_focus focus up,    movefocus, u
bindd = $mod, Down,  $grp_focus focus down,  movefocus, d

# Cycle focus (like Alt+Tab):
bindd = $modAlt, Tab, $grp_focus cycle focus, cyclenext

# Workspaces:
bindd = $mod, 1, $grp_ws workspace 1, workspace, 1
bindd = $mod, 2, $grp_ws workspace 2, workspace, 2
bindd = $mod, 3, $grp_ws workspace 3, workspace, 3
bindd = $mod, 4, $grp_ws workspace 4, workspace, 4

# Move active window to workspace:
bindd = $modAlt, 1, $grp_ws move to workspace 1, movetoworkspace, 1
bindd = $modAlt, 2, $grp_ws move to workspace 2, movetoworkspace, 2
bindd = $modAlt, 3, $grp_ws move to workspace 3, movetoworkspace, 3
bindd = $modAlt, 4, $grp_ws move to workspace 4, movetoworkspace, 4

# Input / Layout:
bindd = $modCtrl, Tab, $grp_input switch keyboard layout, exec, hyprctl switchxkblayout all next

# * Utilities:
# Screenshots (hyprshot required)
bindd = , Print,          $grp_utils screenshot full,   exec, hyprshot -m window
bindd = $modShift, Print, $grp_utils screenshot region, exec, hyprshot -m region
bindd = $modCtrl, Print,  $grp_utils screenshot output, exec, hyprshot -m output
