# Status bar and notifications:
exec-once = waybar
exec-once = swaync

# Daemon services:
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = pipewire & pipewire-pulse & wireplumber & hyprpaper

# Lock screen:
exec-once = hypridle
exec-once = hyprlock

# Network:
exec-once = nm-applet

# Load wallpaper with awww:
# exec-once = awww-daemon
