# Startup configuration

# * Status bar and notifications:
exec-once = waybar
exec-once = mako

# * Daemon services:
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = pipewire & pipewire-pulse & wireplumber
exec-once = hypridle

# * Lock screen:
# exec-once = hypridle
exec-once = hyprlock

# * Network:
exec-once = nm-applet

# * Terminal:
exec-once = kitty

# * Load wallpaper with swww:
exec-once = swww-daemon
