# Core modifiers:
$mod = SUPER
$modAlt = ALT
$modShift = SHIFT
$modCtrl = CTRL

# Default applications:
$term = kitty
$termAlt = foot
$fileManager = nautilus
$launcher = wofi --show drun
$browser = app.zen_browser.zen # flatpak version
$browserAlt = firefox
$editor = codium

# Paths (important for scripts):
$home = ~
$config = ~/.config
$scripts = ~/.config/hypr/scripts
$wallpapers = ~/Wallpapers

# Quality-of-life aliases:
$reload = hyprctl reload
$exit = hyprctl dispatch exit
$killActive = hyprctl dispatch killactive
