windowrule = opacity 0.94 $& 0.94 $& 1,match:class ^(firefox)$
windowrule = opacity 0.94 $& 0.94 $& 1,match:class ^(zen)$
windowrule = opacity 0.94 $& 0.94 $& 1,match:class ^(brave-browser)$
# # windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(codium)$
# windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(code-url-handler)$
# windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(code-insiders-url-handler)$
windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(kitty)$
windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(foot)$
windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(nautilus)$
# windowrule = opacity 0.90 0.90,match:class ^(discord)$ # Discord-Electron
# windowrule = float true,match:title ^(Friends List)$ # Steam Friends List
# windowrule = float true,match:title ^(Steam Settings)$ # Steam Settings
