# windowrulev2 = opacity 0.85 0.85, class: ^(kitty)$ <DEPRECATED>
#
# Convert to actual window and layer rules(v3) visit: https://itsohen.github.io/hyprrulefix/


windowrule = move 20 40, opacity 0.94 0.94, match:class ^(kitty)
windowrule = float center, match:class ^(thunar)
windowrule = float center, match:title ^(File|Open|Save|Confirm|Preferences)
windowrule = float center, match:title ^(.*(authentication|password).*)
windowrule = float center, match:class ^(wofi)
windowrule = opacity 0.94 0.94, match:class ^(waybar)

